import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const OutfitFont = Outfit({

  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${OutfitFont.className}  h-full antialiased`}
    >
      <body >
        <Navbar/>
        <main className="max-w-11/12 mx-auto">{children}</main>
        <Footer/>
        </body>
    </html>
  );
}
